### ISSUE TITLE
which version

### ISSUE THREAD

**Issue by kongdd** [Undi123/SCEUA-Julia#1]
Just wondering which version is this SCEUA, `Duan2005` or `Yarpiz2015`?
Thanks for your awesome work!

**Comment by Undi123** [comment]
I think it’s more like Yapiz.


发自我的iPhone

------------------ Original ------------------
From: Dongdong Kong ***@***.***&gt;
Date: 周日,6月 19,2022 17:21
To: Undi123/SCEUA-Julia ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Undi123/SCEUA-Julia] which version (Issue #1)





 
Just wondering which version is this SCEUA, Duan2005 or Yarpiz2015?
 Thanks for your awesome work!

**Comment by kongdd** [comment]
Thanks for your quick response.
